# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4fsyCX0BSGwQydZBDPTkrT3papjsPm2
"""

import pandas as pd
teacher=pd.DataFrame({
    'FISH': [  'Qadamova Zulayho', "Karimov S", " Azizov I", "Ibragimov N", "Xusanova M", "Muxtarov N" , "Turayeva M" , "Raxmonov SH" ],
    "Fani" : [  "Sun'iy intellekt asoslari", "Sun'iy intellekt asoslari", "Sotib olish tamoyillari","Mikroiqtisodiyot ", "Kiberxavfsizlik asoslari" ,"Mikroiqtisodiyot ", "Sotib olish tamoyillari", "Kiberxavfsizlik asoslari" ],
    "Mashg'ulot turi": [  'amaliy', "ma'ruza", "ma'ruza" ,"ma'ruza" , "ma'ruza",   'amaliy',   'amaliy',   'amaliy'    ],
    "Kafedrasi":[   'Axborot texnologiyalari', 'Axborot texnologiyalari', "Gumanitar fanlar",  "Gumanitar fanlar", "Kiberxavfsizlik", "Gumanitar fanlar",  "Gumanitar fanlar" , "Kiberxavfsizlik", ]
})
print(teacher)

teacher.to_excel("660-guruh teacher's.xlsx")

